name: full_stack_todo
packages:
  - app/*
  - app/server/packages/*

scripts:
  server:dev:
    run: melos exec --fail-fast -- "dart_frog dev"
    description: Starts the dev server for the backend
    select-package:
      flutter: false
      depends-on: dart_frog

  gen:select:
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    description: Runs build_runner on all packages that depends on it
    select-package:
      depends-on: build_runner
  gen:
    run: melos run gen:select --no-select
  gen:watch:
    run: melos exec -- dart pub run build_runner watch --delete-conflicting-outputs
    description: Runs build_runner watcher on selected package
    select-package:
      depends-on: build_runner
