name: shared_models
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0

dependencies:
  exceptions:
    path: ../../app/server/packages/exceptions
  failures:
    path: ../../app/server/packages/failures
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  typedefs:
    path: ../../app/server/packages/typedefs
  uuid_type: ^2.0.0
  validator:
    path: ../../app/server/packages/validator
