name: backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dart_frog: ^0.3.0
  data_source:
    path: ../../packages/data_source
  database:
    path: ../../packages/database
  dotenv: ^4.1.0
  either_dart: ^0.3.0
  exceptions:
    path: ../../packages/exceptions
  failures:
    path: ../../packages/failures
  http: ^0.13.5
  models:
    path: ../../packages/models
  repository:
    path: ../../packages/repository
  typedefs:
    path: ../../packages/typedefs

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
