name: repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0

dependencies:
  bcrypt: ^1.1.2
  data_source:
    path: ../data_source
  either_dart: ^0.3.0
  exceptions:
    path: ../exceptions
  failures:
    path: ../failures
  models:
    path: ../models
  typedefs:
    path: ../typedefs
